### PR TITLE
Bug/30 - Create app form not displaying error messages

### LINKED ISSUE #30: Create App form is not displaying error messages
Create App form is not displaying error messages when you hit submit without filling the form.

### PR DESCRIPTION
**Pull request by alvaro9210**
- Fixed #30  - Create App form is not displaying error messages
 - Added navigation to new app after it was created successfully

### CODE REVIEW

File: src/my-apps/create-app/create-app.component.ts [hunk 1]
```diff
@@ -111,6 +105,8 @@ export class CreateAppComponent implements OnInit {
 			return persistedAppDocument.getACL();
 		} ).then( ( [acl,response]:[ Auth.PersistedACL.Class, HTTP.Response.Class ] )=> {
 			return this.grantAccess( acl );
+		} ).then( ()=> {
+			this.submitting = false;
 		} ).catch( ( error:HTTP.Errors.Error ) => {
 			console.error( error );
```
Comment (MiguelAraCo) [inline src/my-apps/create-app/create-app.component.ts]: If an error happens the form will no longer be in "submitting" mode. Shouldn't we return the value to false too?
